### ISSUE TITLE
Pas de données pour Bourgogne-Franche-Comté

### ISSUE THREAD

**Issue by DavidBruant** [betagouv/indice_pollution#11]
API retourne systématiquement une erreur

**Comment by DavidBruant** [comment]
Bon, bah on scrappe

**Comment by DavidBruant** [comment]
https://www.atmo-bfc.org/yonne/auxerre génère une requête HTTP qui retourne un JSON qui contient des fragments de HTML dont l'un contient l'indice que l'on cherche
Piece of cake!

**Comment by l-vincent-l** [comment]
Done!
