### ISSUE TITLE
Faire un état des lieux de la donnée du lendemain

### ISSUE THREAD

**Issue by l-vincent-l** [betagouv/indice_pollution#62]
Pour chacun des types de données, et le cas échéant, chacune des régions, vérifier si on récupère la donnée du lendemain.

**Comment by fcoufour** [comment]
- La qualité de l'air du lendemain est bien publiée par la totalité des AASQA, cf. pour les plus grandes villes de France : https://docs.google.com/spreadsheets/d/1f44IsfGopDIQBm17YsHW2_Q8MBf4Vt1O5nu9uKKQJNY
- RAEP : vérifier si mardi matin, on a bien déjà les prévisions de la semaine à venir qui commence le mercredi. Vérifier également si on reçoit bien des données 2 fois par semaine
- Vigilance météo : se positionner au max sur le lendemain avant 16h pour avoir la prévision de la veille
- Indice UV : récupérer prévision uv_j1 du jour J pour avoir le jour J+1
- Eaux de baignade : N/A
- Radon : N/A
